name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          pyinstaller --name "Verble" --add-data "words;words" --icon "icon.ico" --onefile --clean src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: verble
          path: dist/Verble

